	function link2WasClicked(event){
		document.getElementById("contents").style.visibility = "visible"
		document.getElementById("body").style.overflow = "visible"
		document.getElementById("home1").style.visibility = "hidden"
		document.getElementById("header1").style.visibility = "hidden"
		document.getElementById("paragraph1").style.visibility = "hidden"
		document.getElementById("paragraph1list").style.visibility = "hidden"
		document.getElementById("transition1").style.visibility = "hidden"
		document.getElementById("header2").style.visibility = "hidden"
		document.getElementById("paragraph2").style.visibility = "hidden"
		document.getElementById("paragraph2list").style.visibility = "hidden"
		document.getElementById("transition2").style.visibility = "hidden"
		document.getElementById("header3").style.visibility = "hidden"
		document.getElementById("paragraph3").style.visibility = "hidden"
		document.getElementById("paragraph3list").style.visibility = "hidden"
		document.getElementById("transition3").style.visibility = "hidden"
		document.getElementById("header4").style.visibility = "hidden"
		document.getElementById("paragraph4").style.visibility = "hidden"
		document.getElementById("transition4").style.visibility = "hidden"
		document.getElementById("header5").style.visibility = "hidden"
		document.getElementById("paragraph5").style.visibility = "hidden"
		document.getElementById("transition5").style.visibility = "hidden"
		document.getElementById("header6").style.visibility = "hidden"
		document.getElementById("paragraph6").style.visibility = "hidden"
		document.getElementById("Lecciones").style.textDecoration = "underline"
		document.getElementById("Inicio").style.textDecoration = "none"
	}
	function transition1(event){
		document.getElementById("header1").style.visibility = "hidden"
		document.getElementById("paragraph1").style.visibility = "hidden"
		document.getElementById("paragraph1list").style.visibility = "hidden"
		document.getElementById("transition1").style.visibility = "hidden"
		document.getElementById("header2").style.visibility = "visible"
		document.getElementById("paragraph2").style.visibility = "visible"
		document.getElementById("paragraph2list").style.visibility = "visible"
		document.getElementById("transition2").style.visibility = "visible"
	}
	function transition2(event){
		document.getElementById("header1").style.visibility = "hidden"
		document.getElementById("paragraph1").style.visibility = "hidden"
		document.getElementById("paragraph1list").style.visibility = "hidden"
		document.getElementById("transition1").style.visibility = "hidden"
		document.getElementById("header2").style.visibility = "hidden"
		document.getElementById("paragraph2").style.visibility = "hidden"
		document.getElementById("paragraph2list").style.visibility = "hidden"
		document.getElementById("transition2").style.visibility = "hidden"
		document.getElementById("header3").style.visibility = "visible"
		document.getElementById("paragraph3").style.visibility = "visible"
		document.getElementById("paragraph3list").style.visibility = "visible"
		document.getElementById("transition3").style.visibility = "visible"
	}
	function transition3(event){
		document.getElementById("header1").style.visibility = "hidden"
		document.getElementById("paragraph1").style.visibility = "hidden"
		document.getElementById("paragraph1list").style.visibility = "hidden"
		document.getElementById("transition1").style.visibility = "hidden"
		document.getElementById("header2").style.visibility = "hidden"
		document.getElementById("paragraph2").style.visibility = "hidden"
		document.getElementById("paragraph2list").style.visibility = "hidden"
		document.getElementById("transition2").style.visibility = "hidden"
		document.getElementById("header3").style.visibility = "hidden"
		document.getElementById("paragraph3").style.visibility = "hidden"
		document.getElementById("paragraph3list").style.visibility = "hidden"
		document.getElementById("transition3").style.visibility = "hidden"
		document.getElementById("header4").style.visibility = "visible"
		document.getElementById("paragraph4").style.visibility = "visible"
		document.getElementById("transition4").style.visibility = "visible"
	}
	function transition4(event){
		document.getElementById("header1").style.visibility = "hidden"
		document.getElementById("paragraph1").style.visibility = "hidden"
		document.getElementById("paragraph1list").style.visibility = "hidden"
		document.getElementById("transition1").style.visibility = "hidden"
		document.getElementById("header2").style.visibility = "hidden"
		document.getElementById("paragraph2").style.visibility = "hidden"
		document.getElementById("paragraph2list").style.visibility = "hidden"
		document.getElementById("transition2").style.visibility = "hidden"
		document.getElementById("header3").style.visibility = "hidden"
		document.getElementById("paragraph3").style.visibility = "hidden"
		document.getElementById("paragraph3list").style.visibility = "hidden"
		document.getElementById("transition3").style.visibility = "hidden"
		document.getElementById("header4").style.visibility = "hidden"
		document.getElementById("paragraph4").style.visibility = "hidden"
		document.getElementById("transition4").style.visibility = "hidden"
		document.getElementById("header5").style.visibility = "visible"
		document.getElementById("paragraph5").style.visibility = "visible"
		document.getElementById("transition5").style.visibility = "visible"
	}
	function transition5(event){
		document.getElementById("header1").style.visibility = "hidden"
		document.getElementById("paragraph1").style.visibility = "hidden"
		document.getElementById("paragraph1list").style.visibility = "hidden"
		document.getElementById("transition1").style.visibility = "hidden"
		document.getElementById("header2").style.visibility = "hidden"
		document.getElementById("paragraph2").style.visibility = "hidden"
		document.getElementById("paragraph2list").style.visibility = "hidden"
		document.getElementById("transition2").style.visibility = "hidden"
		document.getElementById("header3").style.visibility = "hidden"
		document.getElementById("paragraph3").style.visibility = "hidden"
		document.getElementById("paragraph3list").style.visibility = "hidden"
		document.getElementById("transition3").style.visibility = "hidden"
		document.getElementById("header4").style.visibility = "hidden"
		document.getElementById("paragraph4").style.visibility = "hidden"
		document.getElementById("transition4").style.visibility = "hidden"
		document.getElementById("header5").style.visibility = "hidden"
		document.getElementById("paragraph5").style.visibility = "hidden"
		document.getElementById("transition5").style.visibility = "hidden"
		document.getElementById("header6").style.visibility = "visible"
		document.getElementById("paragraph6").style.visibility = "visible"
	}